CREATE TABLE ALUNO 
( 
  ID_ALUNO INT PRIMARY KEY,  
  NOME_ALUNO VARCHAR(100),  
  EMAIL_ALUNO VARCHAR(100),  
  ARROBA_ALUNO VARCHAR(100),  
  DATA_CADASTRO DATE,  
  NIVEL INT,  
  NIVEL_ESCRITA INT,  
  OFENSIVA INT,  
  QI INT,  
  VOCABULARIO INT
); 

CREATE TABLE BASE_CONHECIMENTO 
( 
  ID_CONTEUDO INT PRIMARY KEY,  
  LINK_CONTEUDO VARCHAR(255),  
  NIVEL_DIFICULDADE INT,  
  ASSUNTO VARCHAR(100)
); 

CREATE TABLE LEITURA 
( 
  ID_LEITURA INT PRIMARY KEY,  
  NOME_LEITURA VARCHAR(100),  
  LINK_LEITURA VARCHAR(255),  
  ASSUNTO_LEITURA VARCHAR(100)
); 

CREATE TABLE SEGUIR 
( 
  ID_ALUNO INT,
  PRIMARY KEY (ID_ALUNO),
  FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO(ID_ALUNO)
); 

CREATE TABLE ATIVIDADE 
( 
  ID_ATIVIDADE INT PRIMARY KEY,  
  PONTUACAO_ATIVIDADE INT,  
  ID_CONTEUDO INT,  
  ID_ALUNO INT,
  FOREIGN KEY (ID_CONTEUDO) REFERENCES BASE_CONHECIMENTO(ID_CONTEUDO),
  FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO(ID_ALUNO)
); 
